version: '3'
services:
#  crm-build-comfort:
#    image: crm-build-comfort:1.2
#    ports:
#      - 8080:8080
#  crm-build-comfort-ui:
#    image: crm-build-comfort-ui:1.0
#    ports:
#      - 8082:8080
  postgres-db:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4:6.10
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=ao.andronov@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
volumes:
  db-data:
    driver: local